import type { Metadata } from "next";
import "../globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import Sidebar from "../components/sidebar";
import { Box } from "@mui/material";
import Header from "../components/header";

export const metadata: Metadata = {
  title: {
    default: "Stockflow",
    template: "%s | Stockflow",
  },
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-[#F9FAFB]">
        <AppRouterCacheProvider>
          <Box
            display="grid"
            gridTemplateAreas={`
              "aside header"
              "aside main"
            `}
            gridTemplateRows="auto 1fr"
            gridTemplateColumns="240px 1fr"
            minHeight="100vh"
          >
            {/* Sidebar */}
            <Box gridArea="aside">
              <Sidebar />
            </Box>

            {/* Header */}
            <Box gridArea="header">
              <Header />
            </Box>

            {/* Main content */}
            <Box gridArea="main" p={2}>
              <main>{children}</main>
            </Box>
          </Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
